/** @type {{ title: string, genres: string[] }[]} */
export const FICTION_FORM_SPECS = [
  {
    title: "Novel",
    genres: [
      "Literary Fiction",
      "Contemporary Fiction",
      "Historical Fiction",
      "Fantasy",
      "Urban Fantasy",
      "Science Fiction",
      "Dystopian",
      "Mystery",
      "Crime & Noir",
      "Thriller",
      "Horror",
      "Romance",
      "Historical Romance",
      "Magical Realism",
      "Adventure",
      "Saga & Family Epic",
      "Western",
      "Young Adult (YA)",
      "Coming-of-Age",
      "Humor & Satire",
    ],
  },
  {
    title: "Novella",
    genres: [
      "Literary Novella",
      "Fantasy",
      "Science Fiction",
      "Mystery & Suspense",
      "Romance Novella",
      "Horror",
      "Psychological",
      "Noir & Crime",
      "Historical Novella",
      "Coming-of-Age",
      "Thriller",
    ],
  },
  {
    title: "Short Story",
    genres: [
      "Literary Fiction",
      "Fantasy",
      "Science Fiction",
      "Mystery",
      "Crime & Noir (Short)",
      "Horror",
      "Romance",
      "Humor & Satire",
      "Slipstream & Weird Fiction",
      "Experimental",
      "Regional & Voice-Driven",
      "Contemporary Life",
      "Magical Realism (Short)",
    ],
  },
  {
    title: "Flash Fiction",
    genres: [
      "Literary Microfiction",
      "Science Fiction Flash",
      "Fantasy Flash",
      "Horror Flash",
      "Humor Flash",
      "Crime Flash",
      "Experimental & Hybrid",
      "Sudden Fiction & Very Short",
      "Social Media / Constraint Form",
    ],
  },
  {
    title: "Graphic Novel & Comics",
    genres: [
      "Superhero",
      "Slice of Life",
      "Memoir & Autobiography (Graphic)",
      "Fantasy & Sword & Sorcery",
      "Horror",
      "Science Fiction",
      "Historical Graphic",
      "Literary Graphic Novel",
      "Manga-Influenced",
      "Crime & Noir (Graphic)",
      "Webcomic Collection",
      "All-Ages & Kids (Graphic Story)",
    ],
  },
  {
    title: "Drama",
    genres: [
      "Tragedy",
      "Comedy",
      "Tragicomedy",
      "Historical Drama",
      "Contemporary Drama",
      "Absurdist & Experimental",
      "Musical Theatre",
      "One-Act & Ten-Minute",
      "Radio & Audio Script",
      "Monologue & Solo Piece",
      "Children's & Youth Theatre",
      "Melodrama (Period)",
    ],
  },
  {
    title: "Poetry",
    genres: [
      "Lyric",
      "Narrative",
      "Epic & Long Poem",
      "Sonnet & Fixed Form",
      "Free Verse",
      "Haiku & Short Form",
      "Ballad",
      "Spoken Word & Performance",
      "Prose Poetry",
      "Contemporary",
      "Classical & Traditional",
      "Concrete & Visual Poetry",
    ],
  },
  {
    title: "Fairy Tale, Myth & Folklore",
    genres: [
      "Fairy Tale Retelling",
      "Original Fairy Tale",
      "Myth Retelling",
      "Legend-Based",
      "Cultural Folklore",
      "Fable & Parable",
      "Tall Tale",
      "Dark Folklore & Gothic Folk",
      "Urban Legend–Style",
    ],
  },
  {
    title: "Children's Fiction",
    genres: [
      "Picture Book (Story)",
      "Early Reader",
      "Chapter Books",
      "Middle Grade",
      "Young YA / Bridge",
      "Bedtime & Read-Aloud",
      "Animal Stories",
      "Fantasy & Magic (Kids)",
      "Adventure (Kids)",
      "School & Friendship",
      "Mystery (Kids)",
      "Humor (Kids)",
    ],
  },
  {
    title: "Anthology (Fiction)",
    genres: [
      "Themed Collection",
      "Single-Author Collection",
      "Best Of / Award Anthology",
      "Genre Showcase",
      "Seasonal or Holiday Stories",
      "Linked Stories (Same World)",
      "Collaborative Collection",
      "Flash & Microfiction Anthology",
    ],
  },
];
