/** @type {{ title: string, genres: string[] }[]} */
export const NONFICTION_FORM_SPECS = [
  {
    title: "Biography",
    genres: [
      "Historical",
      "Political",
      "Literary",
      "Celebrity",
      "Science & Medicine",
      "Military",
      "Sports",
      "Art & Music",
    ],
  },
  {
    title: "Memoir",
    genres: [
      "Family & Relationships",
      "Travel",
      "War & Conflict",
      "Addiction & Recovery",
      "Career & Profession",
      "Immigration & Identity",
      "Coming-of-Age",
      "Illness & Healing",
      "Food & Cooking Life",
      "Wilderness & Survival",
    ],
  },
  {
    title: "Autobiography",
    genres: [
      "Political Figure",
      "Artist & Entertainer",
      "Athlete",
      "Scientist & Scholar",
      "Business Leader",
      "Ordinary Life / Everyperson",
      "War & Service",
      "Activist & Reform",
    ],
  },
  {
    title: "Essay",
    genres: [
      "Literary",
      "Personal",
      "Political",
      "Academic",
      "Cultural Criticism",
      "Nature & Environment",
      "Opinion / Commentary",
      "Humor & Satire",
    ],
  },
  {
    title: "History",
    genres: [
      "Ancient World",
      "Medieval",
      "Early Modern",
      "Modern Era",
      "World Wars",
      "National / Regional",
      "Social & Cultural",
      "Military",
      "Economic & Labor",
      "Cold War to Present",
    ],
  },
  {
    title: "Science & Nature",
    genres: [
      "Popular Science",
      "Life Sciences",
      "Physical Sciences",
      "Medicine & Health",
      "Psychology & Behavior",
      "Technology & Computing",
      "Nature & Ecology",
      "Astronomy & Space",
      "Mathematics (General Audience)",
      "Climate & Environment",
    ],
  },
  {
    title: "Self-Help",
    genres: [
      "Personal Development",
      "Relationships & Communication",
      "Productivity & Habits",
      "Mindfulness & Mental Wellness",
      "Career & Work",
      "Creativity & Motivation",
      "Money & Simple Finance",
      "Parenting & Family",
    ],
  },
  {
    title: "True Crime",
    genres: [
      "Cold Case",
      "Courtroom & Trial",
      "Organized Crime",
      "Heist & Fraud",
      "Serial & Pattern Offenses",
      "Investigative Deep Dive",
      "Historical Crime",
      "White-Collar",
    ],
  },
  {
    title: "Travel",
    genres: [
      "Guidebook",
      "Narrative Travel",
      "Adventure & Expedition",
      "Regional Focus",
      "Culinary Travel",
      "Budget & Backpacking",
      "Road Trip & Overland",
      "City & Urban",
    ],
  },
  {
    title: "Business & Economics",
    genres: [
      "Leadership",
      "Entrepreneurship & Startups",
      "Management & Teams",
      "Marketing & Sales",
      "Investing & Markets",
      "Strategy",
      "Industry & Company Stories",
      "Economics (General Audience)",
      "Personal Finance & Wealth",
    ],
  },
  {
    title: "Philosophy",
    genres: [
      "Ethics & Moral Philosophy",
      "Political Philosophy",
      "Existentialism & Meaning",
      "Eastern Traditions",
      "Western Classics",
      "Epistemology & Logic (Intro)",
      "Philosophy of Mind",
      "Contemporary & Applied",
    ],
  },
  {
    title: "Politics & Current Affairs",
    genres: [
      "Domestic Policy",
      "International Relations",
      "Elections & Campaigns",
      "Commentary & Opinion",
      "Geopolitics",
      "Public Policy",
      "Media & Democracy",
      "Social Movements",
    ],
  },
  {
    title: "Religion & Spirituality",
    genres: [
      "Comparative Religion",
      "Theology",
      "Sacred Texts & Commentary",
      "Spirituality (General)",
      "Christianity",
      "Islam",
      "Judaism",
      "Buddhism & Hindu Traditions",
      "Meditation & Practice",
    ],
  },
  {
    title: "Reference & How-To",
    genres: [
      "Encyclopedia & Compendium",
      "Dictionary & Language",
      "Technical Manual",
      "Home, Garden & DIY",
      "Computing & Software How-To",
      "Study & Test Prep",
      "Legal & Consumer Guide",
      "Almanac & Facts",
    ],
  },
  {
    title: "Journalism & Reportage",
    genres: [
      "Longform Feature",
      "Investigative",
      "War & Conflict Reporting",
      "Profile & Interview Collection",
      "Documentary Narrative",
      "Sports Journalism",
      "Science & Environment Reporting",
      "Photo Essay Companion",
    ],
  },
  {
    title: "Education & Teaching",
    genres: [
      "Teaching Practice",
      "Curriculum & Lesson Design",
      "Higher Education",
      "Education Policy",
      "Homeschooling",
      "Study Skills & Learning Science",
      "Literacy & Language Teaching",
      "Special Education",
      "Classroom Management",
    ],
  },
  {
    title: "Art, Design & Photography",
    genres: [
      "Art History",
      "Contemporary Art",
      "Design & Typography",
      "Photography",
      "Architecture",
      "Graphic Design & Illustration",
      "Film & Cinema Studies",
      "Museum & Exhibition",
    ],
  },
  {
    title: "Health & Medicine",
    genres: [
      "Nutrition & Diet",
      "Fitness & Exercise",
      "Sleep & Recovery",
      "Mental Health (Popular)",
      "Chronic Conditions & Recovery",
      "Public Health & Healthcare",
      "Aging & Longevity",
      "Women's & Men's Health",
      "Parenting & Child Health",
    ],
  },
  {
    title: "Law & Society",
    genres: [
      "Introduction to Law",
      "Civil Rights & Liberties",
      "Criminal Justice",
      "Constitutional & Supreme Court",
      "International & Human Rights Law",
      "Legal History",
      "Consumer & Everyday Law",
      "Corporate & Compliance (General Audience)",
    ],
  },
  {
    title: "Children's Nonfiction",
    genres: [
      "Science & STEM",
      "History & Social Studies",
      "Biography for Young Readers",
      "Animals & Nature",
      "Activity, Crafts & How-To",
      "Concepts & Early Learning",
      "Sports & Hobbies",
      "Dinosaurs & World Records",
    ],
  },
  {
    title: "Sports & Recreation",
    genres: [
      "Team Sports",
      "Individual & Endurance Sports",
      "Coaching & Training",
      "Outdoor & Adventure Sports",
      "Olympics & Major Events",
      "Sports History",
      "Rules, Strategy & Analytics",
      "Extreme & Action Sports",
    ],
  },
  {
    title: "Technology & Computing",
    genres: [
      "Programming & Software",
      "Web & Mobile",
      "AI & Machine Learning (Intro)",
      "Cybersecurity & Privacy",
      "Hardware & Gadgets",
      "Product & UX",
      "Tech Industry & Startups",
      "Digital Society & Ethics",
    ],
  },
  {
    title: "Food & Drink",
    genres: [
      "Cookbook",
      "Baking & Pastry",
      "Regional & World Cuisine",
      "Wine, Beer & Spirits",
      "Food Writing & History",
      "Nutrition & Special Diets",
      "Restaurant & Chef Memoir-Adjacent",
      "Vegetarian & Vegan",
    ],
  },
  {
    title: "Anthology & Collected Works",
    genres: [
      "Mixed Essays & Articles",
      "Thematic Collection",
      "Year's Best / Series",
      "Academic Reader",
      "Letters & Correspondence",
      "Short Nonfiction Pieces",
    ],
  },
  {
    title: "Speech, Letters & Documents",
    genres: [
      "Political & Civic",
      "Literary & Commencement",
      "Historical Documents",
      "Debates & Transcripts",
      "Eulogies & Occasional",
      "Manifestos & Calls to Action",
    ],
  },
];
